### ISSUE TITLE
Can't get it to work for Win or Mac

### ISSUE THREAD

**Issue by Rhettrhett123** [pdemange/FireSpoof#2]
Traceback (most recent call last):
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dylan\Desktop\firespoof.py", line 90, in <module>
    spoofPhone(str(argv[1]), str(argv[2]), str(argv[3]), str(argv[4]))
  File "C:\Users\Dylan\Desktop\firespoof.py", line 25, in __init__
    self.s = webdriver.Firefox(profile)
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 148, in __init__
    self.service.start()
  File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by pdemange** [comment]
```Python
Traceback (most recent call last):
File "C:\Users\Dylan\Desktop\firespoof.py", line 90, in
spoofPhone(str(argv[1]), str(argv[2]), str(argv[3]), str(argv[4]))
File "C:\Users\Dylan\Desktop\firespoof.py", line 25, in init
self.s = webdriver.Firefox(profile)
File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 148, in init
self.service.start()
File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

This error is saying that the necessary geckodriver for selenium cannot be found in your PATH. 

```Python
Traceback (most recent call last):
File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
stdin=PIPE)
File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in init
restore_signals, start_new_session)
File "C:\Users\Dylan\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
This error is just confirming that the geckodriver necessary for selenium isn't installed.

No worries! There's an easy fix for this, just download and install the geckodriver for the browser to use with selenium. Here's the link to the aformentioned driver:

https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

And here's a link to a stackoverflow post that will walk you through parts of the installation in case you're having trouble:

https://stackoverflow.com/questions/41190989/how-do-i-install-geckodriver

Hope that helps!

**Comment by Rhettrhett123** [comment]
Fixed by updating Firefox.
